---
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
        pr_assignee: andrewcole
        pr_label: release
name: Automatic Create Pull Request
on:
  push:
    branches:
    - development
